// Authorization-wiring tests: execute real mutations through the real schema +
// graphql-shield layer as an UNAUTHENTICATED request, and assert each is
// rejected. A unit test can confirm a permission rule returns false in
// isolation, but only executing through the wired schema proves the rule is
// actually attached to the operation — catching "correct rule, wrong field"
// leaks and accidental removal of the `Mutation: { "*": deny }` default.
//
// Deny paths resolve entirely within graphql-shield, so these need no database.

import test, { before, after } from "node:test";
import assert from "node:assert/strict";
import { graphql, type GraphQLSchema } from "graphql";
import type { Driver } from "neo4j-driver";
import {
  buildPermissionedSchema,
  makeRequestContext,
} from "../helpers/buildPermissionedSchema.js";
import { ERROR_MESSAGES } from "../../rules/errorMessages.js";

let schema: GraphQLSchema;
let driver: Driver;
let ogm: any;

before(async () => {
  ({ schema, driver, ogm } = await buildPermissionedSchema());
}, { timeout: 120000 });

after(async () => {
  await driver.close();
});

const execUnauthenticated = (source: string) =>
  graphql({
    schema,
    source,
    contextValue: makeRequestContext({ isMutation: true, driver, ogm }),
  });

// delete<Type>s mutations take only an optional `where`, so these are valid
// GraphQL with no inputs — any error is therefore an auth error, not a
// validation error. Every one is gated `and(isAuthenticated, ...)`.
const authGatedDeletes = [
  "deleteUsers",
  "deleteDiscussions",
  "deleteEvents",
  "deleteComments",
  "deleteChannels",
];

for (const mutation of authGatedDeletes) {
  test(`${mutation} is rejected for an unauthenticated request`, async () => {
    const result = await execUnauthenticated(
      `mutation { ${mutation} { nodesDeleted } }`
    );

    assert.ok(
      result.errors && result.errors.length > 0,
      `${mutation} should error when unauthenticated`
    );
    assert.equal(
      result.errors[0].message,
      ERROR_MESSAGES.channel.notAuthenticated,
      `${mutation} should fail with the not-authenticated error, got: ${result.errors[0].message}`
    );
    // A denied top-level mutation nulls the entire data payload — the resolver
    // never ran.
    assert.equal(result.data, null);
  });
}

// Mutations mapped directly to `deny` must be blocked outright. The `deny` rule
// short-circuits before isAuthenticated, so shield returns its default
// "Not Authorised!" fallback. Asserting that exact message also distinguishes a
// real denial from a "Cannot query field" validation error (which would mean
// the mutation doesn't exist and the test is vacuous).
const explicitlyDenied = ["deleteTextVersions", "deleteNotifications"];

for (const mutation of explicitlyDenied) {
  test(`${mutation} is blocked by its explicit deny rule`, async () => {
    const result = await execUnauthenticated(
      `mutation { ${mutation} { nodesDeleted } }`
    );

    assert.ok(result.errors && result.errors.length > 0);
    assert.match(
      result.errors[0].message,
      /Not Authoris/i,
      `${mutation} should hit shield's deny fallback, got: ${result.errors[0].message}`
    );
    assert.equal(result.data, null);
  });
}

// Generated mutations that nobody listed in the shield map must fall through to
// `Mutation: { "*": deny }`. deleteTags is generated by Neo4jGraphQL but absent
// from permissions.ts — if the default-deny were ever removed, this would start
// resolving instead of erroring.
const unmappedGenerated = ["deleteTags"];

for (const mutation of unmappedGenerated) {
  test(`${mutation} is blocked by the default Mutation "*": deny`, async () => {
    const result = await execUnauthenticated(
      `mutation { ${mutation} { nodesDeleted } }`
    );

    assert.ok(result.errors && result.errors.length > 0);
    assert.match(
      result.errors[0].message,
      /Not Authoris/i,
      `${mutation} should hit the default-deny fallback, got: ${result.errors[0].message}`
    );
    assert.equal(result.data, null);
  });
}

// The image/profile report mutations are now wired (previously absent from
// permissions.ts and thus hitting the default deny). Each is gated
// `and(isAuthenticated, ...)`, so an unauthenticated request must fail with the
// not-authenticated error — NOT the "Not Authorised!" default-deny fallback.
// This distinguishes "wired but unauthenticated" from "still default-denied".
const authGatedReports: Array<{ name: string; op: string }> = [
  {
    name: "reportImage",
    op: `mutation { reportImage(imageId: "i", reportText: "t", selectedForumRules: [], selectedServerRules: []) { id } }`,
  },
  {
    name: "reportChannelImage",
    op: `mutation { reportChannelImage(channelUniqueName: "c", imageType: ICON, reportText: "t", selectedServerRules: []) { id } }`,
  },
  {
    name: "reportProfilePicture",
    op: `mutation { reportProfilePicture(username: "u", reportText: "t", selectedServerRules: []) { id } }`,
  },
];

for (const { name, op } of authGatedReports) {
  test(`${name} is wired (unauthenticated -> notAuthenticated, not default-deny)`, async () => {
    const result = await execUnauthenticated(op);

    assert.ok(result.errors && result.errors.length > 0, `${name} should error`);
    assert.equal(
      result.errors[0].message,
      ERROR_MESSAGES.channel.notAuthenticated,
      `${name} should be auth-gated, got: ${result.errors[0].message}`
    );
    // Issue is nullable, so a denied field nulls itself (rather than all of data).
    assert.equal((result.data as Record<string, unknown> | null)?.[name], null);
  });
}

// The image archive/remove mutations are gated `and(isAuthenticated, <perm>)`
// (canArchiveAndUnarchiveImage / canPermanentlyRemoveImage). Like the reports
// above, an unauthenticated request must fail with the not-authenticated error
// rather than the "Not Authorised!" default-deny fallback — proving the rule is
// actually attached, not that the mutation is unmapped.
const authGatedImageMod: Array<{ name: string; op: string }> = [
  {
    name: "archiveImage",
    op: `mutation { archiveImage(imageId: "i", selectedForumRules: [], selectedServerRules: [], reportText: "t") { id } }`,
  },
  {
    name: "unarchiveImage",
    op: `mutation { unarchiveImage(imageId: "i") { id } }`,
  },
  {
    name: "permanentlyRemoveImage",
    op: `mutation { permanentlyRemoveImage(imageId: "i") { id } }`,
  },
];

for (const { name, op } of authGatedImageMod) {
  test(`${name} is wired (unauthenticated -> notAuthenticated, not default-deny)`, async () => {
    const result = await execUnauthenticated(op);

    assert.ok(result.errors && result.errors.length > 0, `${name} should error`);
    assert.equal(
      result.errors[0].message,
      ERROR_MESSAGES.channel.notAuthenticated,
      `${name} should be auth-gated, got: ${result.errors[0].message}`
    );
    assert.equal((result.data as Record<string, unknown> | null)?.[name], null);
  });
}
